#!/usr/bin/python3

from charmhelpers.core import hookenv
import jaascharm
from status import charm_status


def relation_changed():
    hostname = hookenv.relation_get('hostname')
    port = hookenv.relation_get('port')
    if not hostname or not port:
        hookenv.status_set('waiting', 'waiting for mongodb relation')
        return
    config = {
        'storage': {
            'type': 'mongodb',
            'address': '{}:{}'.format(hostname, port),
        },
    }
    jaascharm.update_config_and_restart(config)


if __name__ == '__main__':
    hookenv.log('db-relation-changed')
    relation_changed()
    jaascharm.update_status(failed_status=charm_status)
