#!/usr/bin/python3

from charmhelpers.core import hookenv
from jaascharm import update_nrpe_config


def relation_changed():
    update_nrpe_config()


if __name__ == '__main__':
    hookenv.log('nrpe-relation-changed')
    relation_changed()
