#!/usr/bin/python3

from charmhelpers.core import hookenv
import jaascharm
from status import charm_status


def relation_changed():
    connection_str = hookenv.relation_get('master')
    if not connection_str:
        hookenv.status_set('waiting', 'waiting for postgres relation')
        return
    config = {
        'storage': {
            'type': 'postgres',
            'connection-string': connection_str,
        },
    }
    jaascharm.update_config_and_restart(config)


if __name__ == '__main__':
    hookenv.log('db-relation-changed')
    relation_changed()
    jaascharm.update_status(failed_status=charm_status)
