#!/usr/bin/python3

import os

from charmhelpers.core import (
    hookenv,
)
import jaascharm


if __name__ == '__main__':
    hookenv.log('upgrade-charm')
    jaascharm.stop()
    jaascharm.install(binary=os.path.join('bin', 'candidsrv'))
