#!/usr/bin/python3

from charmhelpers.core import hookenv
from jaascharm import HTTP_LISTEN_PORT


def relation_joined():
    hookenv.relation_set(port=HTTP_LISTEN_PORT)


if __name__ == '__main__':
    hookenv.log('website-relation-joined')
    relation_joined()
