// The code in this file was automatically generated by running httprequest-generate-client.
// DO NOT EDIT

package meeting

import (
	"github.com/juju/httprequest"
	"golang.org/x/net/context"
)

type client struct {
	Client httprequest.Client
}

func (c *client) Done(ctx context.Context, p *doneRequest) error {
	return c.Client.Call(ctx, p, nil)
}

func (c *client) Wait(ctx context.Context, p *waitRequest) (*waitData, error) {
	var r *waitData
	err := c.Client.Call(ctx, p, &r)
	return r, err
}
