// The code in this file was automatically generated by running
// 	httprequest-generate-client . handler client
// DO NOT EDIT

package meeting

import (
	"github.com/juju/httprequest"
)

type client struct {
	Client httprequest.Client
}

func (c *client) Done(p *doneRequest) error {
	return c.Client.Call(p, nil)
}

func (c *client) Wait(p *waitRequest) (*waitData, error) {
	var r *waitData
	err := c.Client.Call(p, &r)
	return r, err
}
