name: candid
summary: Candid Identity Manager
description: Candid Identity Manager
grade: stable
confinement: strict
base: core20
adopt-info: candid # Version our app via set-version within an override

apps:
  candidsrv:
    command: wrappers/candidsrv
    daemon: simple
    plugs:
     - network
     - network-bind
  candid:
    command: wrappers/candid
    plugs:
     - home
     - network

parts:
  # Candid
  candid:
    plugin: nil
    source: .
    source-type: git
    build-packages:
     - bzr
     - gcc
     - git
    build-snaps:
     - go
    stage-packages:
      - jq
    prime:
     - bin/bakery-keygen
     - bin/candid
     - bin/candidsrv
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags --dirty --abbrev=0)"
      go mod download
    override-build: |
      set -ex
      GIT_COMMIT=`git -C $SNAPCRAFT_PART_SRC rev-parse --verify HEAD`
      GIT_VERSION=`git -C $SNAPCRAFT_PART_SRC describe --dirty`
      cp version/init.go.tmpl version/init.go
      gofmt -w -r "unknownVersion -> Version{GitCommit: \"${GIT_COMMIT}\", Version: \"${GIT_VERSION}\",}" version/init.go
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install github.com/canonical/candid/cmd/candid
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install github.com/canonical/candid/cmd/candidsrv
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install gopkg.in/macaroon-bakery.v2/cmd/bakery-keygen@latest

  www-static:
    plugin: dump
    source: ./static
    source-type: local
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/www/static
      mv ./* $SNAPCRAFT_PART_INSTALL/www/static

  www-templates:
    plugin: dump
    source: ./templates
    source-type: local
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/www/templates
      mv ./* $SNAPCRAFT_PART_INSTALL/www/templates

  local:
    plugin: dump
    source: snap/local/
    prime:
     - config
     - wrappers
