name: candid
version: git
summary: Candid Identity Manager
description: Candid Identity Manager
grade: stable
confinement: strict
base: core

apps:
  candidsrv:
    command: wrappers/candidsrv
    daemon: simple
    plugs:
     - network
     - network-bind
  candid:
    command: wrappers/candid
    plugs:
     - home
     - network

parts:
  # Candid
  candid:
    plugin: nil
    source: .
    source-type: git
    build-packages:
     - bzr
     - gcc
    build-snaps:
     - go
    prime:
     - bin/bakery-keygen
     - bin/candid
     - bin/candidsrv
    override-pull: |
      snapcraftctl pull
      go mod download
    override-build: |
      set -ex
      GIT_COMMIT=`git -C $SNAPCRAFT_PART_SRC rev-parse --verify HEAD`
      GIT_VERSION=`git -C $SNAPCRAFT_PART_SRC describe --dirty`
      cp version/init.go.tmpl version/init.go
      gofmt -w -r "unknownVersion -> Version{GitCommit: \"${GIT_COMMIT}\", Version: \"${GIT_VERSION}\",}" version/init.go
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install github.com/canonical/candid/v2/cmd/candid
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install github.com/canonical/candid/v2/cmd/candidsrv
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install gopkg.in/macaroon-bakery.v3/cmd/bakery-keygen

  jq:
    plugin: dump
    source: .
    stage-packages:
     - jq
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
    prime:
     - bin/jq
     - lib/*/libonig.so*
     - lib/*/libjq.so*

  local:
    plugin: dump
    source: snap/local/
    prime:
     - config
     - wrappers

  www:
    plugin: dump
    source: .
    organize:
      static: www/static/
      templates: www/templates/
    prime:
     - www
