name: candid
summary: Candid Identity Manager
description: Candid Identity Manager
grade: stable
confinement: strict
base: core20
adopt-info: candid # Version our app via set-version within an override

parts:
  # Candid
  candid:
    plugin: nil
    source: ./
    source-type: local
    organize:
      candidsrv: bin/
    build-packages:
     - bzr
     - gcc
    build-snaps:
     - go
    prime:
     - bin/bakery-keygen
     - bin/candid
     - bin/candidsrv
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags --dirty --abbrev=0)"
      go mod download
    override-build: |
      set -ex
      GIT_COMMIT=`git -C $SNAPCRAFT_PART_SRC rev-parse --verify HEAD`
      GIT_VERSION=`git -C $SNAPCRAFT_PART_SRC describe --dirty`
      cp version/init.go.tmpl version/init.go
      gofmt -w -r "unknownVersion -> Version{GitCommit: \"${GIT_COMMIT}\", Version: \"${GIT_VERSION}\",}" version/init.go
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install github.com/canonical/candid/cmd/candid
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install github.com/canonical/candid/cmd/candidsrv
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install gopkg.in/macaroon-bakery.v2/cmd/bakery-keygen@latest

  www-static:
    plugin: dump
    source: ./static
    organize:
      static: www/static/

  www-templates:
    plugin: dump
    source: ./templates
    organize:
      templates: www/templates/


  # Dump scripts required to configure candidsrv
  scripts:
    plugin: dump
    source: ./snap/local/scripts
    organize: 
      # Place wrapper in bin such that it can be called easily
      wrapper.sh: bin/
      manage_config.sh: scripts/
      handle_schema_upgrade.sh: bin/
      handle_schema_version_check.sh: bin/
    filesets: 
      include:
        - bin/wrapper.sh
        - scripts/manage_config.sh
        - bin/handle_schema_upgrade.sh
        - bin/handle_schema_version_check.sh
    stage:
      - $include

  # Dump hooks, allow us to run preliminary hooks if we require such behaviour
  hooks:
    plugin: dump
    source: ./snap/local/hooks
    stage-snaps:
    - yq
    stage-packages:
    - jq
    organize: 
      configure: snap/hooks/

apps:
  candidsrv:
    command: bin/wrapper.sh
    daemon: simple
    install-mode: disable
    plugs:
      - "network" # Enables net interface writing (clients)
      - "network-bind" # Enables socket binding
  candid:
    command: bin/candid
    plugs:
     - home
     - network
